function gainStruct = gainBuilder(kP, kI, kD)
gainStruct = struct();
[gainStruct.kP_T, gainStruct.kP_phi, gainStruct.kP_theta, ...
    gainStruct.kP_R, gainStruct.kP_P, gainStruct.kP_Y] = deal(kP(1), kP(2), kP(3), ...
    kP(4), kP(5), kP(6));

[gainStruct.kI_T, gainStruct.kI_phi, gainStruct.kI_theta, ...
    gainStruct.kI_R, gainStruct.kI_P, gainStruct.kI_Y] = deal(kI(1), kI(2), kI(3), ...
    kI(4), kI(5), kI(6));

[gainStruct.kD_T, gainStruct.kD_phi, gainStruct.kD_theta, ...
    gainStruct.kD_R, gainStruct.kD_P, gainStruct.kD_Y] = deal(kD(1), kD(2), kD(3), ...
    kD(4), kD(5), kD(6));
end
